# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

minimum_pre_commit_version: "2.7.1"

default_language_version:
    python: python3.7

repos:
-   repo: meta
    hooks:
    -   id: check-useless-excludes
