# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

minimum_pre_commit_version: '2.7.1'

default_language_version:
    python: python3.7

repos:
-   repo: meta
    hooks:
    -   id: check-useless-excludes


# Fixers

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
        exclude_types: [svg]
    -   id: mixed-line-ending
        args: ['--fix=lf']
    -   id: end-of-file-fixer
        exclude_types: [svg]

-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.9
    hooks:
    -   id: remove-crlf
        types: [text]
        exclude_types: [svg]
    -   id: remove-tabs
        types: [text]
        exclude_types: [svg]
        args: ['--whitespaces-count', '2']  # defaults to: 4


# Checkers

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=1025']
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-xml
    -   id: check-yaml
    -   id: no-commit-to-branch
        args: [--branch, master, --branch, legacy, --pattern, 'v?\d{1,3}\.x']

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.6.0
    hooks:
    -   id: text-unicode-replacement-char
