# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

minimum_pre_commit_version: '2.7.1'

default_language_version:
  python: python3.7

default_stages: [commit]


repos:
# Meta checks
- repo: meta
  hooks:
  - id: check-useless-excludes

# General fixers
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
    exclude_types: [svg]
  - id: mixed-line-ending
    name: Fix mixed line endings
    args: [--fix=lf]
  - id: end-of-file-fixer
    exclude_types: [svg]

# More general fixers
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.9
  hooks:
  - id: remove-tabs
    name: Replace tabs with spaces
    types: [text]
    exclude_types: [svg]
    args: [--whitespaces-count, '2']

# Check and fix spelling
- repo: https://github.com/codespell-project/codespell
  rev: v1.17.1
  hooks:
  # Define separate hooks for checking and correcting spelling errors
  # since codespell doesn't print verbose output when writing changes
  - id: codespell
    name: Check spelling
    exclude: '\.gitattributes'
    args: [--enable-colors, --check-filenames, --check-hidden]
  - id: codespell
    name: Fix spelling
    exclude: '\.gitattributes'
    args: [--enable-colors, --check-filenames, --check-hidden, --write-changes]

# Prettify Bash scripts
- repo: https://github.com/lovesegfault/beautysh
  rev: '6.0.1'
  hooks:
  - id: beautysh
    name: Beautify Bash scripts

# Lint Bash scripts
- repo: https://github.com/openstack/bashate
  rev: '2.0.0'
  hooks:
  - id: bashate
    verbose: false
    name: Lint Bash scripts
    args: [--max-line-length, '80']

# Pretty-format INI
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v1.5.0
  hooks:
  - id: pretty-format-ini
    name: Prettify INI
    types: [text]
    files: '\.(ini|lektorproject|codespellrc)$'
    exclude: 'configs/disqus-comments\.ini'
    args: [--autofix]

# Check JSON, TOML and XML
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-json
  - id: check-toml
  - id: check-xml

# Pretty-format YAML
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v1.5.0
  hooks:
  - id: pretty-format-yaml
    name: Prettify Yaml
    args: [--autofix, --indent, '2', --preserve-quotes]

# Check YAML
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-yaml

# Lint YAML
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.25.0
  hooks:
  - id: yamllint
    name: Lint Yaml
    types: [yaml]
    args: [-s, -f, colored]

# Replace CRLF with LF post-prettify
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.9
  hooks:
  - id: remove-crlf
    name: Replace CRLFs with LF
    types: [text]
    exclude_types: [svg]


# General checkers

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.6.0
  hooks:
  - id: text-unicode-replacement-char
    name: Check for Unicode replacement chars

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-added-large-files
    args: [--maxkb=1025]
  - id: check-byte-order-marker
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-symlinks
  - id: no-commit-to-branch
    name: Prevent commits to wrong branch
    args: [--branch, master, --branch, legacy, --pattern, 'v?\d{1,3}\.x']


# Commit message hooks #

# Check that commit message follows basic rules
- repo: https://github.com/jorisroovers/gitlint
  rev: v0.13.1
  hooks:
  - id: gitlint
    name: Check commit message

# Check commit message spelling
- repo: https://github.com/codespell-project/codespell
  rev: v1.17.1
  hooks:
  - id: codespell
    name: Check commit message spelling
    stages: [commit-msg]
    args: [--enable-colors]
