# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

minimum_pre_commit_version: '2.7.1'

default_language_version:
    python: python3.7

default_stages: [commit]


# Meta checks

repos:
-   repo: meta
    hooks:
    -   id: check-useless-excludes


# General fixers

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
        exclude_types: [svg]
    -   id: mixed-line-ending
        name: Fix mixed line endings
        args: ['--fix=lf']
    -   id: end-of-file-fixer
        exclude_types: [svg]

-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.9
    hooks:
    -   id: remove-crlf
        name: Replace CRLF EoLs with LF
        types: [text]
        exclude_types: [svg]
    -   id: remove-tabs
        name: Replace tabs with spaces
        types: [text]
        exclude_types: [svg]
        args: ['--whitespaces-count', '2']

-   repo: https://github.com/codespell-project/codespell
    rev: 'v1.17.1'
    hooks:
    # Define separate hooks for checking and correcting spelling errors
    # since codespell doesn't print verbose output when writing changes
    -   id: codespell
        name: Check spelling
        exclude: '\.gitattributes'
        args: [--enable-colors, --check-filenames, --check-hidden]
    -   id: codespell
        name: Fix spelling
        exclude: '\.gitattributes'
        args: [--enable-colors, --check-filenames, --check-hidden, --write-changes]

# Language-specific fixers

-   repo: https://github.com/lovesegfault/beautysh
    rev: '6.0.1'
    hooks:
    -   id: beautysh
        name: Beautify shell scripts


# General checkers

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=1025']
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-xml
    -   id: check-yaml
    -   id: no-commit-to-branch
        name: Prevent commits to wrong branch
        args: [--branch, master, --branch, legacy, --pattern, 'v?\d{1,3}\.x']

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.6.0
    hooks:
    -   id: text-unicode-replacement-char
        name: Check for Unicode replacement chars

# Language-specific checkers

-   repo: https://github.com/openstack/bashate
    rev: '2.0.0'
    hooks:
    -   id: bashate
        verbose: false
        name: Lint shell scripts
        args: [--max-line-length, '80']


# Commit message hooks

-   repo: https://github.com/jorisroovers/gitlint
    rev: v0.13.1
    hooks:
    -   id: gitlint
        name: Check commit message
