language: python
python: 3.6
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds
install:
  - "pip install -U pip"
  - "pip install -r requirements.txt"
script: "lektor build --no-prune"

deploy:
  - provider: script
    script: "lektor deploy develop"
    on:
       branch: develop
  - provider: script
    script: "lektor deploy production"
    on:
       branch: production

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2d23c08216a7b3f1a005
