language: python
python: 3.7

install: "ci/install.sh"

script: "ci/build.sh"

deploy:
  - provider: script
    skip_cleanup: true
    script: "lektor deploy develop --output-path website-spyder-build"
    on:
       branch: develop
  - provider: script
    skip_cleanup: true
    script: "lektor deploy production --output-path website-spyder-build"
    on:
       branch: production

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2d23c08216a7b3f1a005
