language: python
python: 3.7

install: "ci/install.sh"

script: "ci/build.sh"

deploy:
  - provider: script
    skip_cleanup: true
    script: "ci/deploy.sh develop"
    on:
       branch: develop
  - provider: script
    skip_cleanup: true
    script: "ci/deploy.sh production"
    on:
       branch: production

notifications:
  webhooks:
    urls:
      - "https://webhooks.gitter.im/e/2d23c08216a7b3f1a005"
