# Build the project and test that it works correctly
# Based on https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Site

on: [pull_request]  # yamllint disable-line rule:truthy

jobs:
  deploy:
    name: Build Site

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Dependencies
      uses: ./.github/actions/setup-and-install
    - name: Build Site
      uses: ./.github/actions/build-project

  pre-commit:
    name: Run Pre-Commit

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Dependencies
      uses: ./.github/actions/setup-and-install
    - name: Run Main Pre-Commit Hooks
      uses: pre-commit/action@v2.0.0
    - name: Run Manual Pre-Commit Checks
      uses: pre-commit/action@v2.0.0
      with:
        extra_args: --all-files --hook-stage manual
